export const STORAGE_KEY = "BEAN_LOG_MASTER_FINAL";
export const RECIPE_STORAGE_KEY = `${STORAGE_KEY}_recipes`;
export const APP_VERSION = "v1.3.5";
export const TAB = { BEANS: 'BEANS', TIMER: 'TIMER', STATS: 'STATS', SETTINGS: 'SETTINGS' };

export const INITIAL_BEAN = { id: null, name: "", country: "", region: "", variety: "", processing: "", altitude: "", roastingLevel: "", producer: "", roastingDate: "", purchaseDate: "", shop: "", purchaseUrl: "", weight: "", price: "", pricePerCup: "", notes: "", flavorDesc: "", memo: "", isFinished: false, isBlend: false, blendInfo: [], mainImage: null, ocrImage: null, tastings: [] };
export const INITIAL_TASTING = { date: new Date().toISOString().split('T')[0], scores: { acidity: 7.0, balance: 7.0, sweetness: 7.0, cleanCup: 7.0, body: 7.0, flavor: 7.0 }, isManualTotal: false, totalScore: 7.0, notes: "", desc: "", memo: "" };
export const INITIAL_RECIPE = { id: null, title: "", bean: "", water: "", interval: "", endTime: "", memo: "" };

export const TASTE_ITEMS = [{ id: 'acidity', label: '산미' }, { id: 'balance', label: '밸런스' }, { id: 'sweetness', label: '단맛' }, { id: 'cleanCup', label: '클린컵' }, { id: 'body', label: '바디' }, { id: 'flavor', label: '아로마' }];
export const SCORE_LABELS_KO = { acidity: "산미", balance: "밸런스", sweetness: "단맛", cleanCup: "클린컵", body: "바디", flavor: "아로마" };

export const FLAVOR_DATA = [
  { id: 'fruity', label: '과일 (Fruity)', color: 'bg-red-500', bg: 'bg-red-50 dark:bg-red-900/20', text: 'text-red-700 dark:text-red-300', subs: [ { group: '베리류 (Berry)', items: ['딸기', '블루베리', '라즈베리', '블랙베리', '크랜베리', '복분자', '산딸기'] }, { group: '감귤류 (Citrus)', items: ['레몬', '라임', '오렌지', '자몽', '귤', '유자', '베르가못', '만다린', '탠저린'] }, { group: '핵과류 (Stone Fruit)', items: ['복숭아', '살구', '자두', '체리', '앵두', '천도복숭아', '자두(Plum)'] }, { group: '열대 과일 (Tropical)', items: ['망고', '파인애플', '바나나', '코코넛', '파파야', '리치', '패션후르츠', '멜론', '수박', '키위'] }, { group: '기타 과일', items: ['사과', '청사과', '배', '포도', '청포도', '머스캣', '석류', '무화과', '토마토'] }, { group: '말린 과일', items: ['건포도', '말린 자두(프룬)', '곶감', '대추', '건무화과'] } ] },
  { id: 'floral', label: '꽃/차 (Floral)', color: 'bg-fuchsia-500', bg: 'bg-fuchsia-50 dark:bg-fuchsia-900/20', text: 'text-fuchsia-700 dark:text-fuchsia-300', subs: [ { group: '꽃 향기', items: ['자스민', '장미', '카모마일', '라벤더', '히비스커스', '아카시아', '엘더플라워', '벚꽃', '목련'] }, { group: '차 (Tea)', items: ['홍차', '녹차', '얼그레이', '우롱차', '말차', '보리차', '허브티'] } ] },
  { id: 'sweet', label: '달콤함 (Sweet)', color: 'bg-orange-400', bg: 'bg-orange-50 dark:bg-orange-900/20', text: 'text-orange-700 dark:text-orange-300', subs: [ { group: '설탕/시럽', items: ['꿀', '흑설탕', '캬라멜', '메이플 시럽', '조청', '당밀', '달고나', '황설탕'] }, { group: '디저트/크림', items: ['바닐라', '버터', '크림', '마시멜로우', '토피', '연유', '커스터드', '생크림'] } ] },
  { id: 'nutty', label: '견과/초코 (Nutty)', color: 'bg-amber-700', bg: 'bg-amber-50 dark:bg-amber-900/20', text: 'text-amber-900 dark:text-amber-300', subs: [ { group: '초콜릿', items: ['다크 초콜릿', '밀크 초콜릿', '카카오닙스', '코코아 파우더', '초코시럽'] }, { group: '견과류', items: ['아몬드', '호두', '땅콩', '헤이즐넛', '피칸', '캐슈넛', '마카다미아', '피스타치오', '밤'] } ] },
  { id: 'roasted', label: '고소함 (Roasted)', color: 'bg-stone-500', bg: 'bg-stone-100 dark:bg-stone-900/20', text: 'text-stone-700 dark:text-stone-300', subs: [ { group: '곡물 (Cereal)', items: ['곡물', '맥아', '볶은 보리', '토스트', '누룽지', '뻥튀기', '비스킷', '라이맥', '오트밀'] }, { group: '로스트 (Roast)', items: ['스모키', '탄맛', '재(Ash)', '타바코', '가죽', '훈제'] }, { group: '감칠맛 (Savory)', items: ['간장', '된장', '팝콘', '버터맛'] } ] },
  { id: 'spices', label: '향신료 (Spices)', color: 'bg-rose-900', bg: 'bg-rose-50 dark:bg-rose-900/20', text: 'text-rose-900 dark:text-rose-300', subs: [ { group: '브라운 스파이스', items: ['시나몬', '정향', '육두구', '아니스', '감초', '계피'] }, { group: '허브/기타', items: ['후추', '생강', '민트', '세이지', '딜', '레몬그라스', '바질', '유칼립투스', '카레'] } ] },
  { id: 'vegetal', label: '채소/지구 (Vegetal)', color: 'bg-green-600', bg: 'bg-green-50 dark:bg-green-900/20', text: 'text-green-700 dark:text-green-300', subs: [ { group: '흙내음 (Earthy)', items: ['흙', '나무(Woody)', '건초', '지푸라기', '버섯', '이끼', '숲바닥'] }, { group: '채소 (Vegetable)', items: ['오이', '완두콩', '호박', '피망', '풀(Grassy)', '올리브', '깻잎'] } ] },
  { id: 'sour', label: '산미/발효 (Sour)', color: 'bg-yellow-500', bg: 'bg-yellow-50 dark:bg-yellow-900/20', text: 'text-yellow-800 dark:text-yellow-300', subs: [ { group: '알콜/발효', items: ['와인', '위스키', '럼', '샴페인', '막걸리', '발효취', '뱅쇼'] }, { group: '산미/기타', items: ['식초', '요거트', '치즈', '시큼한', '고무', '약품'] } ] }
];

export const DEMO_IMG_1 = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjIwMCIgaGVpZ2h0PSIyMDAiIGZpbGw9IiNmM2Y0ZjYiLz48ZyB0cmFuc2Zvcm09InRyYW5zbGF0ZSg1MCA1MCkiPjxnIGZpbGw9IiNGRkYiIHN0cm9rZT0iI0QxRDVEQiIgc3Ryb2tlLXdpZHRoPSIyIj48Y2lyY2xlIGN4PSI1MCIgY3k9IjMwIiByPSIxMiIvPjxjaXJjbGUgY3g9IjY5IiBjeT0iNDMiIHI9IjEyIi8+PGNpcmNsZSBjeD0iNjIiIGN5PSI2NSIgcj0iMTIiLz48Y2lyY2xlIGN4PSIzOCIgY3k9IjY1IiByPSIxMiIvPjxjaXJjbGUgY3g9IjMxIiBjeT0iNDMiIHI9IjEyIi8+PC9nPjxjaXJjbGUgY3g9IjUwIiBjeT0iNTAiIHI9IjEwIiBmaWxsPSIjRkJCRjI0Ii8+PC9nPjwvc3ZnPg==';
export const DEMO_IMG_2 = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjIwMCIgaGVpZ2h0PSIyMDAiIGZpbGw9IiNmM2Y0ZjYiLz48ZyB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxMDAgMTAwKSIgc3Ryb2tlPSIjRkJCRjI0IiBzdHJva2Utd2lkdGg9IjgiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCI+PGNpcmNsZSBjeD0iMCIgY3k9IjAiIHI9IjMwIiBmaWxsPSIjRkJCRjI0IiBzdHJva2U9Im5vbmUiLz48bGluZSB4MT0iMCIgeTE9Ii00MCIgeDI9IjAiIHkyPSItNTUiIC8+PGxpbmUgeDE9IjAiIHkxPSI0MCIgeDI9IjAiIHkyPSI1NSIgLz48bGluZSB4MT0iLTQwIiB5MT0iMCIgeDI9Ii01NSIgeTI9IjAiIC8+PGxpbmUgeDE9IjQwIiB5MT0iMCIgeDI9IjU1IiB5Mj0iMCIgLz48bGluZSB4MT0iLTI4LjI4IiB5MT0iLTI4LjI4IiB4Mj0iLTM4Ljg5IiB5Mj0iLTM4Ljg5IiAvPjxsaW5lIHgxPSIyOC4yOCIgeTE9IjI4LjI4IiB4Mj0iMzguODkiIHkyPSIzOC44OSIgLz48bGluZSB4MT0iLTI4LjI4IiB5MT0iMjguMjgiIHgyPSItMzguODkiIHkyPSIzOC44OSIgLz48bGluZSB4MT0iMjguMjgiIHkxPSItMjguMjgiIHgyPSIzOC44OSIgeTI9Ii0zOC44OSIgLz48L2c+PC9zdmc+';